In [1]:
import numpy as np

# Import danych

In [2]:
train_file_path = "../data/iris_trn.txt"
test_file_path = "../data/iris_tst.txt"

train_data = np.genfromtxt(train_file_path, delimiter="  ", skip_header=1, dtype=np.float128)
test_data = np.genfromtxt(test_file_path, delimiter="  ", skip_header=1, dtype=np.float128)
train_data

array([[1. , 5.1, 3.5, 1.4, 0.2],
       [1. , 4.9, 3. , 1.4, 0.2],
       [1. , 4.7, 3.2, 1.3, 0.2],
       [1. , 4.6, 3.1, 1.5, 0.2],
       [1. , 5. , 3.6, 1.4, 0.2],
       [1. , 5.4, 3.9, 1.7, 0.4],
       [1. , 4.6, 3.4, 1.4, 0.3],
       [1. , 5. , 3.4, 1.5, 0.2],
       [1. , 4.4, 2.9, 1.4, 0.2],
       [1. , 4.9, 3.1, 1.5, 0.1],
       [1. , 5.4, 3.7, 1.5, 0.2],
       [1. , 4.8, 3.4, 1.6, 0.2],
       [1. , 4.8, 3. , 1.4, 0.1],
       [1. , 4.3, 3. , 1.1, 0.1],
       [1. , 5.8, 4. , 1.2, 0.2],
       [1. , 5.7, 4.4, 1.5, 0.4],
       [1. , 5.4, 3.9, 1.3, 0.4],
       [1. , 5.1, 3.5, 1.4, 0.3],
       [1. , 5.7, 3.8, 1.7, 0.3],
       [1. , 5.1, 3.8, 1.5, 0.3],
       [1. , 5.4, 3.4, 1.7, 0.2],
       [1. , 5.1, 3.7, 1.5, 0.4],
       [1. , 4.6, 3.6, 1. , 0.2],
       [1. , 5.1, 3.3, 1.7, 0.5],
       [1. , 4.8, 3.4, 1.9, 0.2],
       [2. , 7. , 3.2, 4.7, 1.4],
       [2. , 6.4, 3.2, 4.5, 1.5],
       [2. , 6.9, 3.1, 4.9, 1.5],
       [2. , 5.5, 2.3, 4. , 1.3],
       [2. , 6

# Class gravity centers

In [3]:
classes = np.unique(train_data[:, 0])
classes

array([1., 2., 3.], dtype=float128)

In [4]:

gravity_centers = []
for class_ in classes:
    # mask class data
    class_data = train_data[train_data[:, 0] == class_]
    #remve class column
    class_data = class_data[:, 1:]
    #mean by column
    class_gravity_centers = np.mean(class_data, axis=0)
    gravity_centers.append(class_gravity_centers)
gravity_centers = np.array(gravity_centers)
gravity_centers

array([[5.028, 3.48 , 1.46 , 0.248],
       [6.012, 2.776, 4.312, 1.344],
       [6.576, 2.928, 5.64 , 2.044]], dtype=float128)

In [5]:
mv = np.mean(train_data[:, 1:], axis=0)
mv

array([5.872     , 3.06133333, 3.804     , 1.212     ], dtype=float128)

In [6]:
sd = np.std(train_data[:, 1:], axis=0, ddof=1)  #excel defualt to one degree of freedom numpy to 0
sd

array([0.85685787, 0.46843423, 1.81498567, 0.76951371], dtype=float128)

In [8]:
gravity_centers_std = (gravity_centers - mv) / sd
gravity_centers_std

array([[-0.98499417,  0.89375762, -1.29147025, -1.25273921],
       [ 0.16338766, -0.60912144,  0.27989202,  0.1715369 ],
       [ 0.82160651, -0.28463619,  1.01157824,  1.08120231]],
      dtype=float128)

# Weights

In [9]:
weigths = gravity_centers_std * 2
weigths

array([[-1.96998833,  1.78751525, -2.58294051, -2.50547842],
       [ 0.32677532, -1.21824287,  0.55978403,  0.34307381],
       [ 1.64321301, -0.56927237,  2.02315647,  2.16240462]],
      dtype=float128)

In [14]:
# additonal column from excel
bias = -np.sum(gravity_centers_std ** 2, axis=1)
bias

array([-5.00626714, -0.5054889 , -2.94834397], dtype=float128)

In [15]:
weigths_std = weigths / sd
weigths_std

array([[-2.29908414,  3.81593641, -1.42311896, -3.25592434],
       [ 0.38136467, -2.60067004,  0.30842339,  0.44583196],
       [ 1.91771947, -1.21526637,  1.11469556,  2.81009238]],
      dtype=float128)

In [20]:
bias_std = bias - np.sum((weigths_std * mv), axis=1)
bias_std

array([  6.17182638,   3.50306473, -18.13499112], dtype=float128)

# Gs

In [23]:
distance_tab = []
for data_row in test_data[:, 1:]:
    distances = []
    for weigth, b in zip(weigths_std, bias_std):
        g = np.sum(data_row * weigth) + b
        distances.append(g)
    distance_tab.append(distances)
distance_tab = np.array(distance_tab)
distance_tab

array([[ 3.19603974e+00, -1.80947823e+00, -9.84666152e+00],
       [ 4.07122943e+00, -2.76057986e+00, -9.77074959e+00],
       [ 4.78650301e+00, -3.06438266e+00, -1.01822204e+01],
       [ 4.54722127e+00, -2.83515799e+00, -1.01721633e+01],
       [ 4.64895226e+00, -2.44402164e+00, -1.06650306e+01],
       [ 4.03745020e+00, -2.14581817e+00, -1.03517321e+01],
       [ 3.29390767e+00, -2.63887633e+00, -9.11513136e+00],
       [ 7.40165729e+00, -4.66936788e+00, -1.11923894e+01],
       [ 6.91024515e+00, -4.80128462e+00, -1.05690605e+01],
       [ 3.94985369e+00, -2.13852404e+00, -1.02714297e+01],
       [ 4.52847460e+00, -2.45298160e+00, -1.05355930e+01],
       [ 4.38140156e+00, -3.01165794e+00, -9.82984364e+00],
       [ 6.32572622e+00, -3.51428460e+00, -1.12715416e+01],
       [ 5.00242590e+00, -2.13082405e+00, -1.13317019e+01],
       [ 4.63481778e+00, -2.84245212e+00, -1.02524657e+01],
       [ 5.20535119e+00, -3.15775707e+00, -1.05076941e+01],
       [ 1.77576957e+00, -2.27635360e-01

In [27]:
mins = np.argmax(distance_tab, axis=1) + 1
mins

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 2])

# Results

In [28]:
correct_count = np.sum(mins == test_data[:, 0])
correct_count

67

In [29]:
incorrect_count = np.sum(mins != test_data[:, 0])
incorrect_count

8