## Definicja algorytmu
1. Wyznacz środki ciężkości a oraz b klasy 1 oraz klasy 2 odpowiednio;
2. Wyznacz hiperpłaszczyznę $g_B(x)=0$ przechodzącą przez punkt b i prostopadłą do wektora o początku b i końcu a, tzn. a-b jest jej wektorem normalnym.
3. Wśród punktów z klasy 1 znajdź punkt c dla którego funkcja $g_B(x)$ osiąga minimum, a wśród punktów z klasy 2 punkt d dla którego funkcja $g_B(x)$ osiąga maksimum, a następnie wyznacz dwie hiperpłaszczyzny $g_C(x)=0$ oraz $g_D(x)=0$ przechodzące odpowiednio przez punkty c i d, równoległe do hiperpłaszczyzny $g_B(x)=0$, tzn. mające wektor a-b jako wektor normalny.
4. Jeżeli punkt c leży po stronie punktu a, a punkt d po stronie punktu b, tj. $g_B(c)>g_B(d)$, to skocz do punktu 8.
5. Jeśli $g_B(c) \ge g_B(d)$, to znajdź liczbę l1 takich punktów x z klasy 1 oraz liczbę l2 takich punktów x z klasy 2, że $g_C(x)\ge -eps$ i $g_D(x)\le eps$ (przyjmij eps=0,0001.
6. Jeżeli $l1>l2$, to usuń punkt d. Gdy zaś $l2>l1$, to usuń punkt c. W przypadku, gdy $l1=l2$ oraz $l1>0$, to usuń zarówno punkt c jak i d.
7. Skocz do punktu 3.
8. Wyznacz funkcję $h(x)=g_C(x)+g_D(x)$.
9. Dokonaj klasyfikacji wszystkich obiektów zbioru uczącego z użyciem otrzymanej w punkcie 8 funkcji dyskryminacyjnej $h(x)$.

In [1]:
import numpy as np
import pandas as pd

In [2]:
train_file_path = "../data/iris_trn.txt"
train_data = pd.read_csv(train_file_path,skiprows=1, index_col=False,skipinitialspace=True, delim_whitespace=True, header=None).to_numpy()
# train_data

In [3]:
class_1 = 2
class_2 =3
classes = [class_1, class_2]

In [4]:
class_1_data = train_data[train_data[:, 0] == class_1][:,1:]
class_2_data = train_data[train_data[:, 0] == class_2][:,1:]
a= np.mean(class_1_data,axis=0)
b= np.mean(class_2_data,axis=0)
plane_vec = a-b

plane_vec

array([-0.564, -0.152, -1.328, -0.7  ])

In [5]:
class_2_data

array([[6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1]])

In [6]:
a,b

(array([6.012, 2.776, 4.312, 1.344]), array([6.576, 2.928, 5.64 , 2.044]))

## Równanie płaszczyzny
Równanie płaszczyzny $\pi$ przechodzącej przez punkt $P_0(x_0,y_0,...) $ i prostopadłej do
wektora niezerowego $\vec{V} = [A,B,C...] $ 
$$ \pi: A(x-x_0)+B(y-y_0)+... = 0$$

## Równanie wektora
Dla dwóch punktów $A(x_a,y_a,...)$ i  $B(x_b,y_b,...)$ wektor normalny ma postać $\vec{V} =[x_a-x_b, y_a - y_b, ... ] $

In [7]:
def get_plane_equatrion(start_point, normal_vetor):
    def plane_equatrion(point):
        return np.inner(normal_vetor,point-start_point)
    return plane_equatrion

gb = get_plane_equatrion(b, plane_vec)

In [8]:
eps = 10**(-5)

In [9]:
while(True):
    c = min(class_1_data, key=gb)
    d = max(class_2_data, key=gb)
    gc  = get_plane_equatrion(c, plane_vec)
    gd = get_plane_equatrion(d, plane_vec)

    if gb(c)>gb(d):
        print("gb(c)>gb(d)")
        break

    l1 = np.sum(gd(class_1_data)<=eps)
    l2 = np.sum(gc(class_2_data)>=-eps)
    index_c = np.flatnonzero(np.all((class_1_data==c), axis=1))[0]
    index_d = np.flatnonzero(np.all((class_2_data == d), axis=1))[0]
    

    if l1<l2:
        print(f"l1({l1})<l2({l2}) removing c={c}")
        class_1_data = np.delete(class_1_data,index_c,axis=0)
    if l1>l2:
        print(f"l1({l1})>l2({l2}) removing d={d}")
        class_2_data = np.delete(class_2_data,index_d,axis=0)
    if l1==l2:
        print(f"l1({l1})==l2({l2}) removing d={d} and c={c}")
        class_1_data = np.delete(class_1_data,index_c,axis=0)
        class_2_data = np.delete(class_2_data,index_d,axis=0)    


l1(16)>l2(6) removing d=[4.9 2.5 4.5 1.7]
l1(5)==l2(5) removing d=[6.  2.2 5.  1.5] and c=[6.9 3.1 4.9 1.5]
l1(1)<l2(2) removing c=[7.  3.2 4.7 1.4]
gb(c)>gb(d)


In [10]:
# c = min(class_1_data, key=gb)
# d = max(class_2_data, key=gb)
# gc  = get_plane_equatrion(c, plane_vec)
# gd = get_plane_equatrion(d, plane_vec)

# # if gb(c)>gb(d):
# #     print("gb(c)>gb(d)")
# #     break

# l1 = np.sum(gd(class_1_data)>=-eps)
# l2 = np.sum(gc(class_2_data)>=eps)
# index_c = np.argwhere(class_1_data == c)[0]
# index_d = np.argwhere(class_2_data == d)[0]

# print(f"Extreme objects index: c={np.argwhere(train_data == c)[0][0]+1} d={np.argwhere(train_data == d)[0][0]}")

In [11]:
train_data[28]

array([2. , 5.5, 2.3, 4. , 1.3])

In [12]:
arrr = np.array([ [1,1],[2,2],[3,2],[4,2],[5,1] ] )

In [13]:
np.flatnonzero()

TypeError: _flatnonzero_dispatcher() missing 1 required positional argument: 'a'

In [ ]:
absolute_index_c = np.flatnonzero(train_data[:,1]==[5])[0]
absolute_index_c

In [ ]:
train_data[:,1]==[5]

In [ ]:
absolute_index_c