# Zadanie 
![image.png](attachment:b6613f22-884a-47ba-ba7c-5c1faeea6861.png)

## Definicja algorytmu
1. Wyznacz środki ciężkości a oraz b klasy 1 oraz klasy 2 odpowiednio;
2. Wyznacz hiperpłaszczyznę $g_B(x)=0$ przechodzącą przez punkt b i prostopadłą do wektora o początku b i końcu a, tzn. a-b jest jej wektorem normalnym.
3. Wśród punktów z klasy 1 znajdź punkt c dla którego funkcja $g_B(x)$ osiąga minimum, a wśród punktów z klasy 2 punkt d dla którego funkcja $g_B(x)$ osiąga maksimum, a następnie wyznacz dwie hiperpłaszczyzny $g_C(x)=0$ oraz $g_D(x)=0$ przechodzące odpowiednio przez punkty c i d, równoległe do hiperpłaszczyzny $g_B(x)=0$, tzn. mające wektor a-b jako wektor normalny.
4. Jeżeli punkt c leży po stronie punktu a, a punkt d po stronie punktu b, tj. $g_B(c)>g_B(d)$, to skocz do punktu 8.
5. Jeśli $g_B(c) \ge g_B(d)$, to znajdź liczbę l1 takich punktów x z klasy 1 oraz liczbę l2 takich punktów x z klasy 2, że $g_C(x)\ge -eps$ i $g_D(x)\le eps$ (przyjmij eps=0,0001.
6. Jeżeli $l1>l2$, to usuń punkt d. Gdy zaś $l2>l1$, to usuń punkt c. W przypadku, gdy $l1=l2$ oraz $l1>0$, to usuń zarówno punkt c jak i d.
7. Skocz do punktu 3.
8. Wyznacz funkcję $h(x)=gC(x)+gD(x)$.
9. Dokonaj klasyfikacji wszystkich obiektów zbioru uczącego z użyciem otrzymanej w punkcie 8 funkcji dyskryminacyjnej $h(x)$.

In [1]:
import numpy as np

In [2]:
train_file_path = "../data/iris_trn.txt"
train_data = np.genfromtxt(train_file_path, delimiter="  ", skip_header=1, dtype=np.float128)
# train_data

In [3]:
train_data[28]

array([2. , 5.5, 2.3, 4. , 1.3], dtype=float128)

In [4]:
class_1 = 2
class_2 =3
classes = [class_1, class_2]

In [17]:
class_1_data = train_data[train_data[:, 0] == class_1][:,1:]
class_2_data = train_data[train_data[:, 0] == class_2][:,1:]
a= np.mean(class_1_data,axis=0)
b= np.mean(class_2_data,axis=0)
plane_vec = a-b

a,b

(array([6.012, 2.776, 4.312, 1.344], dtype=float128),
 array([6.576, 2.928, 5.64 , 2.044], dtype=float128))

## Równanie płaszczyzny
Równanie płaszczyzny $\pi$ przechodzącej przez punkt $P_0(x_0,y_0,...) $ i prostopadłej do
wektora niezerowego $\vec{V} = [A,B,C...] $ 
$$ \pi: A(x-x_0)+B(y-y_0)+... = 0$$

## Równanie wektora
Dla dwóch punktów $A(x_a,y_a,...)$ i  $B(x_b,y_b,...)$ wektor normalny ma postać $\vec{V} =[x_a-x_b, y_a - y_b, ... ] $

In [18]:
def get_plane_equatrion(start_point, normal_vetor):
    def plane_equatrion(point):
        return np.inner(normal_vetor,point-start_point )
    return plane_equatrion

gb = get_plane_equatrion(b, plane_vec)

In [19]:

eps = 10**(-5)

In [20]:
c = min(class_1_data, key=gb)
d = max(class_2_data, key=gb)
gc  = get_plane_equatrion(c, plane_vec)
gd = get_plane_equatrion(d, plane_vec)

# if gb(c)>gb(d):
#     break

l1 = np.sum(gc(class_1_data)>=-eps)
l2 = np.sum(gd(class_2_data)<=eps)

l1,l2    


(25, 25)

In [9]:
class_1_data

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3]], dtype=float128)

In [10]:
c,d

(array([4.9, 2.4, 3.3, 1. ], dtype=float128),
 array([7.7, 2.6, 6.9, 2.3], dtype=float128))

In [11]:
train_data[19]

array([1. , 5.1, 3.8, 1.5, 0.3], dtype=float128)

In [12]:
a,b

(array([6.012, 2.776, 4.312, 1.344], dtype=float128),
 array([6.576, 2.928, 5.64 , 2.044], dtype=float128))

In [13]:
class_1_data

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3]], dtype=float128)

In [14]:
for p in zip(sorted(class_1_data, key=gb)):
    print(f"{p}={gb(p)}")

(array([4.9, 2.4, 3.3, 1. ], dtype=float128),)=[-2.269056]
(array([5. , 2. , 3.5, 1. ], dtype=float128),)=[-2.007856]
(array([5.6, 2.9, 3.6, 1.3], dtype=float128),)=[-1.189856]
(array([5.6, 2.5, 3.9, 1.1], dtype=float128),)=[-0.992256]
(array([5.2, 2.7, 3.9, 1.4], dtype=float128),)=[-0.977456]
(array([5.5, 2.3, 4. , 1.3], dtype=float128),)=[-0.806256]
(array([6. , 2.2, 4. , 1. ], dtype=float128),)=[-0.749456]
(array([5.8, 2.7, 4.1, 1. ], dtype=float128),)=[-0.653456]
(array([6.1, 2.8, 4. , 1.3], dtype=float128),)=[-0.391856]
(array([5.9, 3. , 4.2, 1.5], dtype=float128),)=[-0.068656]
(array([5.7, 2.8, 4.5, 1.3], dtype=float128),)=[0.046544]
(array([5.6, 3. , 4.5, 1.5], dtype=float128),)=[0.160544]
(array([6.4, 2.9, 4.3, 1.3], dtype=float128),)=[0.190944]
(array([6.2, 2.2, 4.5, 1.5], dtype=float128),)=[0.377344]
(array([6.1, 2.8, 4.7, 1.2], dtype=float128),)=[0.467744]
(array([6.7, 3.1, 4.4, 1.4], dtype=float128),)=[0.593344]
(array([6.1, 2.9, 4.7, 1.4], dtype=float128),)=[0.622944]
(arr

In [15]:
train_data[28]

array([2. , 5.5, 2.3, 4. , 1.3], dtype=float128)

In [16]:
train_data[]

SyntaxError: invalid syntax (454059604.py, line 1)

In [ ]:
gb(np.array([ 5.5, 2.3, 4. , 1.3]))

In [ ]:
gb(np.array(np.array([6.9, 3.1, 4.9, 1.5])))